name: binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - sympy
  - statsmodels
  - pip:
      - dataframe_image
